#!/bin/bash

cat /etc/passwd | grep '/home/' | \
grep -v 'cups\|syslog' | cut -d ':' -f 1 > /tmp/homes.list

while read USUARIO; do
	runuser -l $USUARIO -c \
	"ln -s /usr/share/simulide/examples /home/$USUARIO/SimulIDE\\ Examples"

	cp /usr/share/applications/simulide-bionic.desktop /home/$USUARIO/Desktop/simulide-bionic.desktop

	runuser -l $USUARIO -c "rm -rf /home/$USUARIO/.cache/"
	if [ -f /usr/bin/lxpanelctl ]; then
		su - $USUARIO -c "lxpanelctl restart"
	fi
done < /tmp/homes.list
