#!/bin/bash

cat /etc/passwd | grep '/home/' | \
grep -v 'cups\|syslog' | cut -d ':' -f 6 > /tmp/homes.list

while read BASEDIR; do
    rm -rf "$BASEDIR/Desktop/simulide-bionic.desktop"
    rm -rf "$BASEDIR/SimulIDE Examples"
done < /tmp/homes.list